### ISSUE TITLE
GasLess not work (coinomi wallet)

### ISSUE THREAD

**Issue by tllambi** [Proof-Of-Humanity/proof-of-humanity-web#490]
I use the coinomi wallet, by pressing "Vouch" it sends me the request to pay the gas of the transaction. But when clicking on "GasLess Vouch" nothing happens, I tried from Chrome, Microsoft Edge from 3 different machines on different networks and from my Android cell phone from Chrome.

![image](https://user-images.githubusercontent.com/14277279/146284452-921a51ce-ae19-4be6-aa95-3b28d6937bd9.png)

**Comment by 0x676f** [comment]
@tilambi Do you see any error messages in your browser's JavaScript Console (Developer Console)?

**Comment by tllambi** [comment]
When I press the button no error appears. 
But these appear when I log in:

wallet connect
DOMException: Failed to execute 'fetch' on 'Window': The user aborted a request.
    at u (https://app.proofofhumanity.id/_next/static/chunks/pages/_app-81a79d61c8fa4b043b7f.js:1:2809705)
    at https://app.proofofhumanity.id/_next/static/chunks/pages/_app-81a79d61c8fa4b043b7f.js:1:2809916
    at l (https://app.proofofhumanity.id/_next/static/chunks/main-106c166f3fb1d9265dcc.js:1:72073)
    at Generator._invoke (https://app.proofofhumanity.id/_next/static/chunks/main-106c166f3fb1d9265dcc.js:1:71861)
    at Generator.next (https://app.proofofhumanity.id/_next/static/chunks/main-106c166f3fb1d9265dcc.js:1:72498)
    at s (https://app.proofofhumanity.id/_next/static/chunks/pages/_app-81a79d61c8fa4b043b7f.js:1:2809390)
    at a (https://app.proofofhumanity.id/_next/static/chunks/pages/_app-81a79d61c8fa4b043b7f.js:1:2810257)
    at https://app.proofofhumanity.id/_next/static/chunks/pages/_app-81a79d61c8fa4b043b7f.js:1:2810316
    at new Promise (<anonymous>)
    at Object.<anonymous> (https://app.proofofhumanity.id/_next/static/chunks/pages/_app-81a79d61c8fa4b043b7f.js:1:2810197)
DOMException: The user aborted a request.

**Comment by 0x676f** [comment]
@tllambi Thank you. My best guess, after seeing your error message, would be that this happens because we do not support Coinomi's Web3 browser.

In general, MetaMask would be the more likely to work for you. The easiest solution would be to install the [MetaMask](https://metamask.io/) extension in your Chrome browser, and then import your existing Ethereum wallet there using your secret recovery phrase.
